### ISSUE TITLE
Error: no matching EC2 VPC found

### ISSUE THREAD

**Issue by mildnl** [eana/bitwarden-tf-aws#105]
Hi,
I never used terraform before and I am stuck on the EC2 VPC error

│ Error: no matching EC2 VPC found
│
│   with module.bitwarden.data.aws_vpc.this,
│   on ../data.tf line 27, in data "aws_vpc" "this":
│   27: data "aws_vpc" "this" {
│

In the requirements you speak of a EC2 Key pair but I don't see where to use it and I assume this is the error.
Could you explain what needs to be done to fix my issue if you have an idea what's causing the problem?

**Comment by eana** [comment]
Hi there! Thanks for reaching out! It seems that the error message you're receiving is not related to the EC2 Key pair, but rather to the [data resource](https://github.com/eana/bitwarden-tf-aws/blob/master/data.tf#L27-L32) attempting to find a VPC named `prod-vpc` or the specified [environment](https://github.com/eana/bitwarden-tf-aws/blob/master/example/main.tf#L22). This is an oversight on my part, and I apologize for this.

I'm working on finding a solution to this issue.

**Comment by eana** [comment]
I have chosen not to implement the feature of creating a VPC from within the module, as it would unnecessarily complicate things. Instead, I have made an update to the example to create a separate VPC for the deployment of the instance. Unfortunately, I haven't been able to test these changes, but if you encounter any problems, please let me know. You can find the details of the update [here](https://github.com/eana/bitwarden-tf-aws/pull/107).
